### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by rodneytamblyn** [harvard-edtech/caccl-lti#18]
Hi there,

Which version of LTI (1.3?) is this using please?

Is this tool specifically only for Canvas or should it work with other LTI compliant LMS such as Moodle?

Thank you.

Rod

**Comment by gabeabrams** [comment]
Great question! I've tested this with LTI 1.1 and have not yet tested it with LTI 1.3. That's not to say that it wouldn't work or couldn't be updated to work with both LTI 1.1 and 1.3, I just haven't had time yet to work on that. I'm open to PRs and suggestions!

The whole caccl project is specifically designed for Canvas, but the caccl-lti module could potentially be used in isolation to handle LTI launches from other LMS's. That said, there are some additional custom parameters that are passed through the LTI launch by Canvas (context and Canvas roles, for example). Thus, information in the launchInfo object might not be fully filled in because some of those fields are Canvas-specific.

If you're just looking for a lib that handles LTI launches, there are other libs, or you could take a look at the code here to see how we're parsing and validating LTI launches.

Hope this helps!
